### ISSUE TITLE
All formula do not show as expected.

### ISSUE THREAD

**Issue by haiyongsong1921** [TensorNetwork/tensornetwork.org#22]
The formula in all docs does not show correctly in browser. How to fix this?

**Comment by emstoudenmire** [comment]
Thanks for reporting this. Could you be more specific though? What browser? Does MathJax (Latex rendering) work in your browser on other websites? Could you post a screenshot?

Since many other people can see the formulas, the most likely issue is that you may need to upgrade your browser or use a different one.

**Comment by haiyongsong1921** [comment]
> Thanks for reporting this. Could you be more specific though? What browser? Does MathJax (Latex rendering) work in your browser on other websites? Could you post a screenshot?
> 
> Since many other people can see the formulas, the most likely issue is that you may need to upgrade your browser or use a different one.

Thanks, I use Safari instead of Chrome, then it works.
