### ISSUE TITLE
New section: applications of tensor networks in statistical physics

### ISSUE THREAD

**Issue by stecrotti** [TensorNetwork/tensornetwork.org#25]
Hi,
While doing work for my research I stumbled upon a number of papers exploring the connection between stochastic dynamics of classical particles and many-body quantum systems. The idea is that some stochastic processes can be mapped onto quantum problems, which can then be tackled via tensor network techniques. 
I think a section on (out-of-equilibrium, classical) statistical physics would be a nice addition to the portal: an introductory section plus pointers to the most relevant works. If people are interested I'm happy to make a PR, let me know!

The connection goes roughly like this: in a wide variety of situations, the time evolution of the state of a physical system with $\mathcal N$ states is described by a master equation
```math
 \frac{d}{dt}p_i(t)= \sum_{j=1}^{\mathcal N} A_{ij}p_j(t)
```
where $p_i(t)$ is the probability of finding the system in state $i$ at time $t$ and $A$ a real-valued matrix.
Knowledge of the eigen-decomposition of $A$ would allow to solve for $p_i(t)$, but this is typically unfeasible because $\mathcal N$ is exponentially large in the size of the system.
It turns out that there are some stochastic processes for which $A=-H$ with $H$ corresponding exactly to the Hamiltonian of some many-body quantum system. If that is the case, any known method for the diagonalization of $H$ applies directly to the original problem. In particular, a quantity that is typically interesting is the steady state $\lim_{t\to\infty}p_i(t)$ which corresponds to the leading eigenvector of $A$, hence to the ground state of $H$.
Once the correspondence has been established, finding the ground state of $H$ can be a job for DMRG. This has been done successfully in many cases, for example to characterize non-equilibrium phase transitions  [Carlon, E., Henkel, M., & Schollwöck, U. (1999). Density matrix renormalization group and reaction-diffusion processes](https://arxiv.org/abs/cond-mat/9902041), more recently to study large deviation properties of the East model [Using matrix product states to study the dynamical large deviations of kinetically constrained models](https://arxiv.org/abs/1903.01570) and in general especially for 1D dynamics, whose corresponding "Hamiltonian" also exhibits 1D structure suitable for diagonalization via Matrix Product States.
There are also cases where a Matrix Product ansatz is exact, above all [Derrida, B., Evans, M. R., Hakim, V., & Pasquier, V. (1993). Exact solution of a 1D asymmetric exclusion model using a matrix formulation](https://iopscience.iop.org/article/10.1088/0305-4470/26/7/011/meta).
More examples are found in [Schollwöck, U. (2004). The density-matrix renormalization group](https://arxiv.org/abs/cond-mat/0409292).

**Comment by emstoudenmire** [comment]
Hi Stefano,
A contribution to the site about this would be very welcome, thanks! Basically if you just adapted the material you wrote above that would already be a nice resource for people wanting to get into that area.

Here are some thoughts about it:
* if you go ahead with this, please break up the PR's into a few smaller contributions rather than one large one as it will be easier for me to review & you can get feedback partway through (unless the contribution is a single small page in which case one PR is fine)
* please put it as a new section under "Applications of Tensor Networks" on the main page
* I think it would be good to emphasize that although the correspondence of H to a Hamiltonian of a quantum system can be made, that the methods also work more generally for any Hermitian matrix H (are non-Hermitian matrices also studied in this subfield?). Basically what I'm getting at, and I'm sure you understand, is that while connecting to quantum physics can be a helpful bridge to existing concepts, that tensor networks are really a more general mathematical tool and can be applied to classical systems and purely mathematical problems without necessarily referring to quantum mechanics too. (E.g. the term "ground state" can be generalized to "dominant eigenvector".)

Looking forward to having any new material you'd like to add –

**Comment by stecrotti** [comment]
Ok great! I'll do it then

I agree about the third point and indeed those H's are often non-Hermitian.
